### ISSUE TITLE
Strange behavior in highlighting `type`

### ISSUE THREAD

**Issue by ricky136973** [yaene/vscode-twelf-lang#2]
Words including `type` will be highlighted on these substrings. For example, `atypebtypec` will be highlighted on two substrings of `type`, while `a`, `b` and `c` remain white. I believe the expected behavior is not to highlight this word.

**Comment by yaene** [comment]
That's right, need to add word boundaries to it so it won't match the keyword when it's a substring.

**Comment by yaene** [comment]
should be fixed in v0.0.5, otherwise reopen, thanks!
